inicio/urls.py
from django.urls import path
from inicio import views

app_name= 'inicio'


urlpatterns = [
    path ('', views.inicio, name = 'inicio'), 
    path ('nosotros/', views.nosotros, name= 'Nosotros'),   
]

proyecto/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include ('inicio.urls')), 
    path('admin/', admin.site.urls),
]

inicio/models.py
from django.db import models

# Create your models here.

inicio/views.py
from django.shortcuts import render

def inicio (request):
    return render (request, 'inicio/inicio.html')


def nosotros (request):
    return render (request , 'inicio/nosotros.html')

inicio/templates/inicio/inicio.html
{% extends 'base.html' %}

{%block title_head%}
<title>Inicio</title>
{% endblock title_head%}
</head>
<body>
{% block contenido %}
<h1>Bienvenidos a mi WEB</h1>
{%endblock contenido %}

inicio/templates/inicio/nosotros.html
{% extends 'base.html' %}

{%block title_head%}
<title>Nosotros</title>
{% endblock title_head%}
</head>
<body>
{% block h1_header %}
<h1>Mis inicios en la programación</h1>
{%endblock h1_header %}


{% block contenido %}
Creador@ de la WEB 
{%endblock contenido   %}

templates/base.html
<!DOCTYPEhtml >
<html  lang =" es ">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"> 
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    
</head>
<body>
   
    
</body>
</html>


<!DOCTYPE html>
<html lang="en">
    {%load static %}
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        {%block title_head%}
        <title>Template Base </title>
        {% endblock title_head%}
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" type="text/css" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href={% static 'css/styles.css'%} rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-light bg-light static-top">
            <div class="container">
                <a class="navbar-brand" href={% url 'inicio:inicio'%}>inicio</a>
                <a class="btn btn-primary" href="#signup">Sign Up</a>
            </div>
        </nav>
        <!-- Masthead-->
        <header class="masthead">
            <div class="container position-relative">
                <div class="row justify-content-center">
                    <div class="col-xl-6">
                        <div class="text-center text-white">
                            {%block h1_header%} 
                            <h1 class="mb-5">Generate more leads with a professional landing page!</h1>
                            {%endblock h1_header%}
                        </div>
                    </div>
                </div>
            </div>
        </header>
        {% block contenido %}
        El BOTY DUERME MUCHO 
        {%endblock contenido   %}
        <!-- Footer-->
        <footer class="footer bg-light">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 h-100 text-center text-lg-start my-auto">
                        <ul class="list-inline mb-2">
                            <li class="list-inline-item"><a href={% url 'inicio:Nosotros' %}>Nosotros</a></li>
                            <li class="list-inline-item">⋅</li>
                            
                        </ul>
                    </div>
                    <div class="col-lg-6 h-100 text-center text-lg-end my-auto">
                        <ul class="list-inline mb-0">
                            <li class="list-inline-item me-4">
                                <a href="#!"><i class="bi-facebook fs-3"></i></a>
                            </li>
                            <li class="list-inline-item me-4">
                                <a href="#!"><i class="bi-twitter fs-3"></i></a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!"><i class="bi-instagram fs-3"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src={% static 'js/scripts.js' %}></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>